# Generated by Django 3.2 on 2022-08-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
