# Generated by Django 3.2 on 2022-08-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='noticia',
            new_name='titulo',
        ),
    ]
