# Generated by Django 3.2 on 2022-08-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
