# Generated by Django 3.2 on 2022-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_delete_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
